/*
 * File: app/view/cntPrincipal.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App_Test_PadronGral.view.cntPrincipal', {
    extend: 'Ext.window.Window',
    alias: 'widget.cntprincipal',

    requires: [
        'App_Test_PadronGral.view.cntPrincipalViewModel',
        'Ext.form.FieldContainer',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.view.Table'
    ],

    viewModel: {
        type: 'cntprincipal'
    },
    autoShow: true,
    height: 569,
    width: 738,
    bodyPadding: 3,
    iconCls: 'x-fa fa-address-book',
    title: 'Padron Gral',

    dockedItems: [
        {
            xtype: 'fieldcontainer',
            dock: 'bottom',
            height: 50,
            itemId: 'cntAceptarCancelar',
            margin: '0 0 0 0',
            style: {
                backgroundColor: 'transparent',
                // Fondo transparente
                borderTop: '2px solid #000',
                // Borde superior sólido
                boxShadow: '0px -2px 4px rgba(0, 0, 0, 0.2)',
                // Sombra debajo del borde
            },
            width: 430,
            layout: {
                type: 'border',
                padding: '4 4 4 4'
            },
            items: [
                {
                    xtype: 'button',
                    region: 'east',
                    itemId: 'cmdAceptar',
                    margin: '5 0 5 5',
                    style: {
                        'box-shadow': '0 2px 4px 0 rgba(0,0,0,.14), 0 1px 18px 0 rgba(0,0,0,.12), 0 3px 5px -1px rgba(0,0,0,.2)',
                        'border-radius': '1px 1px 1px 1px',
                        
                    },
                    width: 94,
                    iconCls: 'x-fa fa-check',
                    text: 'Aceptar'
                },
                {
                    xtype: 'button',
                    region: 'east',
                    itemId: 'cmdCancelar',
                    margin: '5 0 5 6',
                    style: {
                        'box-shadow': '0 2px 4px 0 rgba(0,0,0,.14), 0 1px 18px 0 rgba(0,0,0,.12), 0 3px 5px -1px rgba(0,0,0,.2)',
                        'border-radius': '1px 1px 1px 1px',
                        
                    },
                    width: 94,
                    iconCls: 'x-fa fa-times',
                    text: 'Cancelar'
                }
            ]
        }
    ],

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'panel',
                        height: 213,
                        style: '// esto es una modificacion desde el Architect',
                        layout: 'anchor',
                        bodyPadding: 10,
                        header: false,
                        title: 'cntpanel',
                        items: [
                            {
                                xtype: 'fieldcontainer',
                                height: 40,
                                itemId: 'cntCirMed',
                                margin: '0 5 3 0',
                                layout: 'column',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        itemId: 'numCM',
                                        margin: '0 5 3 0',
                                        width: 184,
                                        fieldLabel: 'Circulo Medico',
                                        hideTrigger: true,
                                        maxValue: 99,
                                        minValue: 1
                                    },
                                    {
                                        xtype: 'button',
                                        height: 34,
                                        itemId: 'btnbuscar',
                                        margin: '0 5 3 0',
                                        width: 32,
                                        iconCls: 'x-fa fa-search',
                                        tooltip: 'Buscar...'
                                    },
                                    {
                                        xtype: 'textfield',
                                        itemId: 'txtCirMed',
                                        margin: '0 5 3 0',
                                        width: 395,
                                        emptyText: '(Sin dato)'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldcontainer',
                                itemId: 'cntProf',
                                margin: '20 0 0 0',
                                width: 140,
                                layout: {
                                    type: 'vbox',
                                    align: 'stretch'
                                },
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        flex: 0,
                                        reference: 'chkMedicos',
                                        itemId: 'chkMedicos',
                                        margin: '0 5 3 0',
                                        width: 32,
                                        fieldLabel: 'Medicos',
                                        labelWidth: 50,
                                        bind: {
                                            disabled: '{chkVeterinarios.checket}'
                                        }
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        reference: 'chkVeterinarios',
                                        itemId: 'chkVeterinarios',
                                        margin: '0 5 3 0',
                                        fieldLabel: 'Solo Veterinarios',
                                        labelWidth: 103,
                                        bind: {
                                            disabled: '{chkMedicos.checket}'
                                        }
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        itemId: 'chkActivos',
                                        margin: '0 5 3 0',
                                        width: 32,
                                        fieldLabel: 'Solo Activos',
                                        labelWidth: 103
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldcontainer',
                                height: 39,
                                itemId: 'cntFecha',
                                margin: '-110 8 3 200',
                                width: 182,
                                layout: 'hbox',
                                labelAlign: 'right',
                                labelWidth: 50,
                                items: [
                                    me.processTxtFecha({
                                        xtype: 'datefield',
                                        flex: 1,
                                        itemId: 'txtFecha',
                                        padding: 3,
                                        width: 159,
                                        fieldLabel: 'Fecha',
                                        labelWidth: 38
                                    })
                                ]
                            },
                            {
                                xtype: 'fieldcontainer',
                                itemId: 'cntDatos',
                                margin: '0 0 0 200',
                                padding: 3,
                                width: 182,
                                labelAlign: 'right',
                                layout: {
                                    type: 'hbox',
                                    align: 'stretch'
                                },
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        itemId: 'chkCUIT',
                                        width: 66,
                                        fieldLabel: 'C.U.I.T',
                                        labelWidth: 66
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        itemId: 'chkNombre',
                                        margin: '30 0 0 -65',
                                        width: 70,
                                        fieldLabel: 'Nombre',
                                        labelWidth: 66
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'gridpanel',
                        margin: '10 0 0 0',
                        style: {
                            borderTop: '2px solid #ADD8E6',
                            // Borde superior sólido
                        },
                        header: false,
                        title: 'My Grid Panel',
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'string',
                                text: 'String'
                            },
                            {
                                xtype: 'numbercolumn',
                                flex: 1,
                                dataIndex: 'number',
                                text: 'Number'
                            },
                            {
                                xtype: 'datecolumn',
                                dataIndex: 'date',
                                text: 'Date'
                            },
                            {
                                xtype: 'booleancolumn',
                                dataIndex: 'bool',
                                text: 'Boolean'
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.self.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processTxtFecha: function(config) {

    }

});