/*
 * File: app/model/datosJson.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App_Test_PadronGral.model.datosJson', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'apellidoNombre'
        },
        {
            name: 'cuit'
        },
        {
            name: 'fechaNacimiento'
        }
    ]
});